platform :ios, '8.0'
use_frameworks!

target 'FlavorFinder' do
pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', :branch => 'swift-2'
pod 'Parse'
pod 'FontAwesome.swift'
pod 'MGSwipeTableCell'
pod 'DZNEmptyDataSet'
pod 'DOFavoriteButton'
pod 'FilterBar', '~>2.0.0'
pod 'ASHorizontalScrollView', '~>1.1'
end

target 'FlavorFinderTests' do

end

