platform :ios, '8.0'
use_frameworks!

target 'FlavorFinder' do
pod 'Parse'
pod 'FontAwesome.swift'
pod 'MGSwipeTableCell'
pod 'DZNEmptyDataSet'
pod 'DOFavoriteButton'
pod 'FilterBar', '~>2.0.0'
pod 'ASHorizontalScrollView', '~>1.1'
pod 'Toast-Swift', '~> 1.0.0'
end

target 'FlavorFinderTests' do

end

